POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": "100",
  "nome": "Ja3434ne",
  "login": "bi343uel002",
  "email": "jaASFne.smith@company.com",
  "cpf": "47804811802",
  "senha": "h2f23",
  "contaBancaria": "43435-x",
  "saldo": 245.9
}


###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": "200",
  "nome": "Jane",
  "login": "biuel002",
  "email": "jane.smith@company.com",
  "cpf": "47804811802",
  "senha": "h2f23",
  "contaBancaria": "43435-x",
  "saldo": 1245.9
}

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": "500",
  "nome": "JaASFASFASFne",
  "login": "biuel002",
  "email": "jane.smith@company.com",
  "cpf": "47804811802",
  "senha": "h2f23",
  "contaBancaria": "43435-x",
  "saldo": 2435.9
}


###
GET http://127.0.0.1:8080/customer
Accept: application/json

###
GET http://127.0.0.1:8080/customer/200
Accept: application/json

###
GET http://127.0.0.1:8080/customer/500
Accept: application/json

###
DELETE http://127.0.0.1:8080/customer/100

###
DELETE http://127.0.0.1:8080/customer/200
